def build(ctx):
	source = [  'Channel.c',
				'Interrupt.c',
				'Map.c',
				'Message.c',
				'NewlibFuncs.c',
				'Object.c',
				'Spawn.c',
				'Start.c',
				'SwiAsm.s']
	ctx.crossobjects(target='system', source=source, use='shared', export_includes='include', includes='include')